# Generated by Django 4.2.3 on 2023-07-31 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.TextField(verbose_name='Имя автора')),
                ('author_surname', models.TextField(verbose_name='Фамилия автора')),
                ('author_middle_name', models.TextField(verbose_name='Отчество автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название произведения')),
                ('number_of_pages', models.IntegerField(verbose_name='Количество страниц')),
                ('barcode', models.IntegerField(verbose_name='Штрих-код')),
                ('publication_date', models.DateField(verbose_name='Дата издания')),
                ('publishing_house', models.TextField(verbose_name='Издательство')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book_issuing.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Описание книги',
                'verbose_name_plural': 'Описание книг',
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_book_name', models.TextField(verbose_name='Имя пользователя')),
                ('user_book_surname', models.TextField(verbose_name='Фамилия пользователя')),
                ('parallel_number', models.IntegerField(verbose_name='Класс')),
                ('letter', models.CharField(max_length=1, verbose_name='Литера класса')),
                ('user_book_email', models.EmailField(max_length=254, verbose_name='Почта пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь книги',
                'verbose_name_plural': 'Пользователи книги',
                'db_table': 'user_book',
            },
        ),
        migrations.CreateModel(
            name='BooksInUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(verbose_name='Статус книги')),
                ('date_of_issue', models.DateTimeField(verbose_name='Дата выдачи')),
                ('date_of_receiving', models.DateTimeField(verbose_name='Дата получения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book_issuing.book', verbose_name='Книга')),
                ('book_owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book_issuing.userbook', verbose_name='Владелец книги')),
            ],
            options={
                'verbose_name': 'Книга в использовании',
                'verbose_name_plural': 'Книги в использовании',
                'db_table': 'books_in_use',
            },
        ),
    ]
