# Generated by Django 4.2.3 on 2023-07-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_issuing', '0002_alter_booksinuse_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Описание книги', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='barcode',
            field=models.TextField(verbose_name='Штрих-код'),
        ),
    ]
